### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by andrewjswan** [victorx64/pr-label#5]
Hi!

I added this GitHub Action, but I get an error when I push:
```
Unhandled exception. System.InvalidOperationException: fatal: no such path mediaportal/Build Release.bat	 in f6078a69b2700e8a41bcdadddc12a72be1239d90

   at devrating.git.GitProcess.Output()
   at devrating.git.GitAFileBlames.InitedBlames()
   at devrating.git.GitAFileBlames.AtLine(UInt32 line)
   at devrating.git.GitDeletions.HunkDeletions(String header)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at devrating.git.GitDeletions.Items()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at devrating.git.GitDiff.ToJson()
   at StabilityMetric.Apply(Diff diff) in /home/runner/work/_actions/victorx64/pr-label/v0/core/StabilityMetric.cs:line 48
   at Program.<Main>$(String[] args) in /home/runner/work/_actions/victorx64/pr-label/v0/on-push/Program.cs:line 28
   at Program.<Main>(String[] args)
Error: Process completed with exit code 1.
```

And at Pull Request I get this error:
```
Unhandled exception. Octokit.ForbiddenException: Resource not accessible by integration
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
   at SizeLabel.CreateLabelsForRepository() in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 64
   at SizeLabel.Update(UInt32 additions) in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 30
   at GitHubClient.UpdatePrLabels(UInt32 size, Double rating, Int32 prNumber) in /home/runner/work/_actions/victorx64/pr-label/v0/core/GitHubClient.cs:line 78
   at Program.<Main>$(String[] args) in /home/runner/work/_actions/victorx64/pr-label/v0/on-pull_request/Program.cs:line 65
   at Program.<Main>(String[] args)
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/issues#create-a-label"}
Error: Process completed with exit code 1.
```

Is there any way to solve this?

**Comment by victorx64** [comment]
@andrewjswan to fix the pull request error you need to add permissions to the workflow:

```yaml
name: Workflow / Size and Stability labels

"on":
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  add-pr-labels:
    name: Size and Stability labels

    permissions: # here
      contents: read
      pull-requests: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Add Size and Stability labels
        uses: victorx64/pr-label@v0
        with:
          # Optional pattern used to limit paths.
          # Example: "'*.js' ':!*.spec.js' .".
          # See https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          git-pathspec: "':!Build/**' ':!**/TuningParameters/**' ':!libbluray'"
```

Thanks for the information! I updated `README.md`.

**Comment by victorx64** [comment]
@andrewjswan the `push` error is fixed. No action is required on your side.

**Comment by andrewjswan** [comment]
> the `push` error is fixed. No action is required on your side.

It seems not quite, I get an error:

```
Unhandled exception. System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling).
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at devrating.git.GitDiff.ToJson()
   at StabilityMetric.Apply(Diff diff) in /home/runner/work/_actions/victorx64/pr-label/v0/core/StabilityMetric.cs:line 48
   at Program.<Main>$(String[] args) in /home/runner/work/_actions/victorx64/pr-label/v0/on-push/Program.cs:line 28
   at Program.<Main>(String[] args)
Error: Process completed with exit code 1.
```

**Comment by victorx64** [comment]
@andrewjswan it should be good now

**Comment by andrewjswan** [comment]
> to fix the pull request error you need to add permissions to the workflow

Strangely enough, I got the error again today.

```
<6>devrating.git.GitProcess[1770264] `/home/runner/work/MediaPortal-1/MediaPortal-1` git, ["diff","6feeb4d07b795b36950f5187319b170a5c468492..c439a00bce17da294c0d102e6e1daae51d4bd6d8","-U0","-w","-M01","--shortstat","--",":!Build/**",":!**/TuningParameters/**",":!libbluray"]
<6>GitHubClient[1006847] PR Additions: `23381`. Rating before this PR: `1500`
Unhandled exception. Octokit.ForbiddenException: Resource not accessible by integration
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
   at SizeLabel.CreateLabelsForRepository() in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 64
   at SizeLabel.Update(UInt32 additions) in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 30
   at GitHubClient.UpdatePrLabels(UInt32 size, Double rating, Int32 prNumber) in /home/runner/work/_actions/victorx64/pr-label/v0/core/GitHubClient.cs:line 78
   at Program.<Main>$(String[] args) in /home/runner/work/_actions/victorx64/pr-label/v0/on-pull_request/Program.cs:line 65
   at Program.<Main>(String[] args)
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/issues#create-a-label"}
Error: Process completed with exit code 1.
```

**Comment by andrewjswan** [comment]
> to fix the pull request error you need to add permissions to the workflow:

Strangely enough, I got the error again today.

```
<6>devrating.git.GitProcess[1770264] `/home/runner/work/MediaPortal-1/MediaPortal-1` git, ["diff","6feeb4d07b795b36950f5187319b170a5c468492..c439a00bce17da294c0d102e6e1daae51d4bd6d8","-U0","-w","-M01","--shortstat","--",":!Build/**",":!**/TuningParameters/**",":!libbluray"]
<6>GitHubClient[1006847] PR Additions: `23381`. Rating before this PR: `1500`
Unhandled exception. Octokit.ForbiddenException: Resource not accessible by integration
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
   at SizeLabel.CreateLabelsForRepository() in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 64
   at SizeLabel.Update(UInt32 additions) in /home/runner/work/_actions/victorx64/pr-label/v0/core/SizeLabel.cs:line 30
   at GitHubClient.UpdatePrLabels(UInt32 size, Double rating, Int32 prNumber) in /home/runner/work/_actions/victorx64/pr-label/v0/core/GitHubClient.cs:line 78
   at Program.<Main>$(String[] args) in /home/runner/work/_actions/victorx64/pr-label/v0/on-pull_request/Program.cs:line 65
   at Program.<Main>(String[] args)
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/issues#create-a-label"}
Error: Process completed with exit code 1.
```

**Comment by victorx64** [comment]
@andrewjswan can you check in https://github.com/andrewjswan/MediaPortal-1/settings/actions if `Send write tokens to...` option is enabled?
![image](https://github.com/victorx64/pr-label/assets/42280354/b6fb7f4b-a148-4c17-9fef-80fce9411f59)

**Comment by andrewjswan** [comment]
I dont see this options, only:
- Actions permissions
- Artifact and log retention
- Fork pull request workflows from outside collaborators
- Workflow permissions

**Comment by andrewjswan** [comment]
Any news?

**Comment by victorx64** [comment]
@andrewjswan I'll try to reproduce this weekend. It seems it happens when PR is made from a fork of a public repository.

**Comment by victorx64** [comment]
@andrewjswan in `.github/workflows/workflow_size_labels.yml` please change `pull_request` to `pull_request_target`.

```yaml
name: Workflow / Size and Stability labels

on:
  pull_request_target:  # <- here
    types: [opened, synchronize]
#  push:
#    branches: [master]

jobs:
  add-labels:
    name: Add labels
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Add Size and Stability labels
        uses: victorx64/pr-label@v0
        with:
          # Optional pattern used to limit paths.
          # See https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          git-pathspec: "':!Build/**' ':!**/TuningParameters/**' ':!libbluray'"
```

**Comment by andrewjswan** [comment]
Look like work ... Thanks!
